# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gh-pages-example',
                'doc_host': 'https://PaoloBova.github.io',
                'git_url': 'https://github.com/PaoloBova/gh-pages-example',
                'lib_path': 'gh_pages_example'},
  'syms': { 'gh_pages_example.core': { 'gh_pages_example.core.fermi_learning': ('core.html#fermi_learning', 'gh_pages_example/core.py'),
                                       'gh_pages_example.core.foo': ('core.html#foo', 'gh_pages_example/core.py')},
            'gh_pages_example.toolbox': { 'gh_pages_example.toolbox.build_transition_matrix': ( 'methods.html#build_transition_matrix',
                                                                                                'gh_pages_example/toolbox.py'),
                                          'gh_pages_example.toolbox.fermi_learning': ( 'methods.html#fermi_learning',
                                                                                       'gh_pages_example/toolbox.py'),
                                          'gh_pages_example.toolbox.fixation_rate': ( 'methods.html#fixation_rate',
                                                                                      'gh_pages_example/toolbox.py')}}}