# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_analysis_dsair.ipynb.

# %% auto 0
__all__ = ['fig1_data']

# %% ../nbs/10_analysis_dsair.ipynb 2
from nbdev.showdoc import *
from fastcore.test import test_eq
from .utils import *
from .methods import *
from .payoffs import *
from .conditions import *
import typing

import numpy as np
import nptyping

# %% ../nbs/10_analysis_dsair.ipynb 6
def fig1_data(b=4, c=1, B=10**4, W=100, β=0.01, Z=100, S=['A','B'], gamma=1):
    """Create parameter grid for the baseline DSAIR model, Figure 1,
    The Anh et al. 2020."""
    namesofvalues=['s','b','c','p','B','W','β','gamma']
    matchingvalues = np.array([[s,b,c,p,B,W,β,gamma]
                               for s in np.arange(1,5.1,0.1)
                               for p in np.arange(0,1.02,0.02)])
    models = {k:v for k, v in zip(namesofvalues, matchingvalues.T)}
    models = {**models,
              'Z':Z, # Z should be a scalar
              'strategy_set':S # S should be a list of strings
             }
    return models
