# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'fermi_learning']

# %% ../nbs/00_core.ipynb 3
import nptyping
import numpy as np

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
def fermi_learning(β:nptyping.NDArray, # learning rate
                   fitnessA:nptyping.NDArray, # fitness of strategy A
                   fitnessB:nptyping.NDArray # fitness of strategy B
                  ) -> nptyping.NDArray:
    """Compute the likelihood that a player with strategy B adopts strategy A using the fermi function."""
    return (1 + np.exp(-β*(fitnessA - fitnessB)))**-1
